In [10]:
# Data extraction
import polars as pl
import glob # pattern matching

# Visualisation
import plotly.express as px

import warnings

warnings.filterwarnings('ignore')

In [11]:
files = sorted(glob.glob('./data/EV__*.parquet'))

lf = pl.scan_parquet(files)
lf.head(10).collect()

shape: (10, 63)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Time      ┆ [29:0]Sch ┆ [29:1]Sch ┆ [29:2]Sch ┆ … ┆ [72:227]S ┆ [72_0]Sch ┆ [72_1]S7- ┆ [72_65]S │
│ ---       ┆ weißmasch ┆ weißmasch ┆ weißmasch ┆   ┆ 7-Schweiß ┆ weißrolle ┆ Schweißma ┆ chweißst │
│ datetime[ ┆ ine -     ┆ ine -     ┆ ine -     ┆   ┆ maschine  ┆ ist unten ┆ schine -  ┆ romregel │
│ ms]       ┆ Einspe…   ┆ Einspe…   ┆ Einspe…   ┆   ┆ - D…      ┆ S…        ┆ Sch…      ┆ ung: R…  │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f32       ┆ f32       ┆ f32       ┆   ┆ f32       ┆ bool      ┆ bool      ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2026-08-3 ┆ -0.106812 ┆ -0.106812 ┆ 0.137329  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.906     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ 0.015259  ┆ 0.015259  ┆ 0.015259  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.907     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ -0.106812 ┆ 0.015259  ┆ 0.015259  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.908     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ 0.015259  ┆ 0.015259  ┆ 0.137329  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.909     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ 0.015259  ┆ -0.106812 ┆ 0.259399  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.910     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ 0.015259  ┆ 0.015259  ┆ 0.015259  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.911     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ 0.015259  ┆ 0.015259  ┆ 0.015259  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.912     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ 0.015259  ┆ 0.015259  ┆ 0.137329  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.913     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ 0.015259  ┆ 0.015259  ┆ 0.015259  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.914     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-08-3 ┆ 0.015259  ┆ 0.015259  ┆ 0.015259  ┆ … ┆ 154.34028 ┆ false     ┆ false     ┆ false    │
│ 1 00:06:3 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 0.915     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
EIN = '[72_1]S7-Schweißmaschine - Schweißen EIN (M215_0)' # target col
 
# 0 --> 1 1 --> 0 
# now & prev                

df_aug = (
    lf.select('Time', EIN).drop_nulls()
    .with_columns(seq_id=(pl.col(EIN) & ~pl.col(EIN).shift(fill_value=False)).cum_sum() - 1)
    .filter(pl.col(EIN))
    .group_by('seq_id').agg(start=pl.col('Time').min(), end=pl.col('Time').max())
    .sort('seq_id').collect(engine='streaming')
)

df_aug

shape: (383, 3)
┌────────┬─────────────────────────┬─────────────────────────┐
│ seq_id ┆ start                   ┆ end                     │
│ ---    ┆ ---                     ┆ ---                     │
│ u32    ┆ datetime[ms]            ┆ datetime[ms]            │
╞════════╪═════════════════════════╪═════════════════════════╡
│ 0      ┆ 2026-08-31 01:46:36.286 ┆ 2026-08-31 01:46:54.475 │
│ 1      ┆ 2026-08-31 02:17:14.776 ┆ 2026-08-31 02:17:24.885 │
│ 2      ┆ 2026-08-31 02:56:21.096 ┆ 2026-08-31 02:56:31.015 │
│ 3      ┆ 2026-08-31 04:18:59.666 ┆ 2026-08-31 04:19:09.495 │
│ 4      ┆ 2026-08-31 05:20:52.826 ┆ 2026-08-31 05:21:02.605 │
│ …      ┆ …                       ┆ …                       │
│ 378    ┆ 2026-09-22 10:17:43.680 ┆ 2026-09-22 10:17:55.799 │
│ 379    ┆ 2026-09-22 11:28:30.910 ┆ 2026-09-22 11:28:43.029 │
│ 380    ┆ 2026-09-22 12:17:06.080 ┆ 2026-09-22 12:17:18.219 │
│ 381    ┆ 2026-09-22 13:00:41.190 ┆ 2026-09-22 13:00:53.319 │
│ 382    ┆ 2026-09-22 13:42:41.840 ┆ 2026-09-22 13:42:53.439 │
└────────┴─────────────────────────┴─────────────────────────┘

In [ ]:
SEQ = 1
s = df_aug.filter(pl.col('seq_id') == SEQ).row(0, named=True)
start_time, end_time = s['start'], s['end']

cols = [c for c in lf.collect_schema().names() if c != 'Time']

df_seq = (
    lf
    .filter(pl.col('Time').is_between(start_time, end_time))
    .select('Time', *cols)
    .with_columns(t=(pl.col('Time') - start_time).dt.total_milliseconds() / 1000)
    .collect(engine='streaming')
)

for i in range(0, len(cols), 8):
    batch = cols[i:i+8]
    fig = px.line(df_seq.select('t', pl.col(batch).cast(pl.Float32)),
                  x='t', y=batch, facet_col='variable', facet_col_wrap=1,
                  height=220 * len(batch), render_mode='webgl')

    fig.update_yaxes(matches=None, title=None)
    fig.update_xaxes(title='Zeit ab Schweißbeginn [s]')
    fig.for_each_annotation(lambda a: a.update(text=a.text.split('=', 1)[1]))
    fig.update_layout(showlegend=False, hovermode='x unified')
    fig.write_image(f'./Images/seq{SEQ + 1}_part{i // 8}.png', width=1500, scale=2)
    fig.show()